default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: postgresql://postgres:@localhost:5433/thr-dev

test:
  <<: *default
  url: postgresql://postgres:@localhost:5433/thr-test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
  sudo ufw status
